# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'EventApp' do

pod 'Parse', '~> 1.7'
pod 'ParseUI', '~> 1.1'
pod 'ParseFacebookUtils', '~> 1.7'
pod 'Google-Maps-iOS-SDK', '~> 1.9'
pod 'pop', '~> 1.0'
pod 'UIColor+FlatColors', '~> 0.0'
pod 'VBFPopFlatButton', '~> 0.0'

end

target 'EventAppTests' do

end

